extend type Mutation {
  """
  ✨ Insert a single `AnswerChoice` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  answerChoice_insert(
    """
    Data object to insert into the table.
    """
    data: AnswerChoice_Data!
  ): AnswerChoice_KeyOutput! @fdc_generated(from: "AnswerChoice", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ContentSourceLink` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  contentSourceLink_insert(
    """
    Data object to insert into the table.
    """
    data: ContentSourceLink_Data!
  ): ContentSourceLink_KeyOutput! @fdc_generated(from: "ContentSourceLink", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Course` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  course_insert(
    """
    Data object to insert into the table.
    """
    data: Course_Data!
  ): Course_KeyOutput! @fdc_generated(from: "Course", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Formula` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  formula_insert(
    """
    Data object to insert into the table.
    """
    data: Formula_Data!
  ): Formula_KeyOutput! @fdc_generated(from: "Formula", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `FormulaSection` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  formulaSection_insert(
    """
    Data object to insert into the table.
    """
    data: FormulaSection_Data!
  ): FormulaSection_KeyOutput! @fdc_generated(from: "FormulaSection", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `GlossaryNote` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  glossaryNote_insert(
    """
    Data object to insert into the table.
    """
    data: GlossaryNote_Data!
  ): GlossaryNote_KeyOutput! @fdc_generated(from: "GlossaryNote", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `GlossaryTerm` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  glossaryTerm_insert(
    """
    Data object to insert into the table.
    """
    data: GlossaryTerm_Data!
  ): GlossaryTerm_KeyOutput! @fdc_generated(from: "GlossaryTerm", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `IngestionJob` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  ingestionJob_insert(
    """
    Data object to insert into the table.
    """
    data: IngestionJob_Data!
  ): IngestionJob_KeyOutput! @fdc_generated(from: "IngestionJob", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Lesson` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  lesson_insert(
    """
    Data object to insert into the table.
    """
    data: Lesson_Data!
  ): Lesson_KeyOutput! @fdc_generated(from: "Lesson", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `LessonNote` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  lessonNote_insert(
    """
    Data object to insert into the table.
    """
    data: LessonNote_Data!
  ): LessonNote_KeyOutput! @fdc_generated(from: "LessonNote", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `LessonVersion` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  lessonVersion_insert(
    """
    Data object to insert into the table.
    """
    data: LessonVersion_Data!
  ): LessonVersion_KeyOutput! @fdc_generated(from: "LessonVersion", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Module` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  module_insert(
    """
    Data object to insert into the table.
    """
    data: Module_Data!
  ): Module_KeyOutput! @fdc_generated(from: "Module", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Question` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  question_insert(
    """
    Data object to insert into the table.
    """
    data: Question_Data!
  ): Question_KeyOutput! @fdc_generated(from: "Question", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Quiz` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quiz_insert(
    """
    Data object to insert into the table.
    """
    data: Quiz_Data!
  ): Quiz_KeyOutput! @fdc_generated(from: "Quiz", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `QuizAttempt` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quizAttempt_insert(
    """
    Data object to insert into the table.
    """
    data: QuizAttempt_Data!
  ): QuizAttempt_KeyOutput! @fdc_generated(from: "QuizAttempt", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `QuizQuestion` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quizQuestion_insert(
    """
    Data object to insert into the table.
    """
    data: QuizQuestion_Data!
  ): QuizQuestion_KeyOutput! @fdc_generated(from: "QuizQuestion", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `QuizResponse` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quizResponse_insert(
    """
    Data object to insert into the table.
    """
    data: QuizResponse_Data!
  ): QuizResponse_KeyOutput! @fdc_generated(from: "QuizResponse", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SourceMaterial` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sourceMaterial_insert(
    """
    Data object to insert into the table.
    """
    data: SourceMaterial_Data!
  ): SourceMaterial_KeyOutput! @fdc_generated(from: "SourceMaterial", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SourceMaterialActivity` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sourceMaterialActivity_insert(
    """
    Data object to insert into the table.
    """
    data: SourceMaterialActivity_Data!
  ): SourceMaterialActivity_KeyOutput! @fdc_generated(from: "SourceMaterialActivity", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SourceMaterialFolder` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sourceMaterialFolder_insert(
    """
    Data object to insert into the table.
    """
    data: SourceMaterialFolder_Data!
  ): SourceMaterialFolder_KeyOutput! @fdc_generated(from: "SourceMaterialFolder", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SourceMaterialTag` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sourceMaterialTag_insert(
    """
    Data object to insert into the table.
    """
    data: SourceMaterialTag_Data!
  ): SourceMaterialTag_KeyOutput! @fdc_generated(from: "SourceMaterialTag", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SourceMaterialTagAssignment` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sourceMaterialTagAssignment_insert(
    """
    Data object to insert into the table.
    """
    data: SourceMaterialTagAssignment_Data!
  ): SourceMaterialTagAssignment_KeyOutput! @fdc_generated(from: "SourceMaterialTagAssignment", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserCourseProgress` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userCourseProgress_insert(
    """
    Data object to insert into the table.
    """
    data: UserCourseProgress_Data!
  ): UserCourseProgress_KeyOutput! @fdc_generated(from: "UserCourseProgress", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserFavorite` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userFavorite_insert(
    """
    Data object to insert into the table.
    """
    data: UserFavorite_Data!
  ): UserFavorite_KeyOutput! @fdc_generated(from: "UserFavorite", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserLessonProgress` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userLessonProgress_insert(
    """
    Data object to insert into the table.
    """
    data: UserLessonProgress_Data!
  ): UserLessonProgress_KeyOutput! @fdc_generated(from: "UserLessonProgress", purpose: INSERT_SINGLE)
  """
  ✨ Insert `AnswerChoice` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  answerChoice_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AnswerChoice_Data!]!
  ): [AnswerChoice_KeyOutput!]! @fdc_generated(from: "AnswerChoice", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ContentSourceLink` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  contentSourceLink_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ContentSourceLink_Data!]!
  ): [ContentSourceLink_KeyOutput!]! @fdc_generated(from: "ContentSourceLink", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Course` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  course_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Course_Data!]!
  ): [Course_KeyOutput!]! @fdc_generated(from: "Course", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Formula` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  formula_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Formula_Data!]!
  ): [Formula_KeyOutput!]! @fdc_generated(from: "Formula", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `FormulaSection` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  formulaSection_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [FormulaSection_Data!]!
  ): [FormulaSection_KeyOutput!]! @fdc_generated(from: "FormulaSection", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `GlossaryNote` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  glossaryNote_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [GlossaryNote_Data!]!
  ): [GlossaryNote_KeyOutput!]! @fdc_generated(from: "GlossaryNote", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `GlossaryTerm` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  glossaryTerm_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [GlossaryTerm_Data!]!
  ): [GlossaryTerm_KeyOutput!]! @fdc_generated(from: "GlossaryTerm", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `IngestionJob` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  ingestionJob_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [IngestionJob_Data!]!
  ): [IngestionJob_KeyOutput!]! @fdc_generated(from: "IngestionJob", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Lesson` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  lesson_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Lesson_Data!]!
  ): [Lesson_KeyOutput!]! @fdc_generated(from: "Lesson", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `LessonNote` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  lessonNote_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [LessonNote_Data!]!
  ): [LessonNote_KeyOutput!]! @fdc_generated(from: "LessonNote", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `LessonVersion` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  lessonVersion_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [LessonVersion_Data!]!
  ): [LessonVersion_KeyOutput!]! @fdc_generated(from: "LessonVersion", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Module` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  module_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Module_Data!]!
  ): [Module_KeyOutput!]! @fdc_generated(from: "Module", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Question` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  question_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Question_Data!]!
  ): [Question_KeyOutput!]! @fdc_generated(from: "Question", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Quiz` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quiz_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Quiz_Data!]!
  ): [Quiz_KeyOutput!]! @fdc_generated(from: "Quiz", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `QuizAttempt` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quizAttempt_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [QuizAttempt_Data!]!
  ): [QuizAttempt_KeyOutput!]! @fdc_generated(from: "QuizAttempt", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `QuizQuestion` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quizQuestion_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [QuizQuestion_Data!]!
  ): [QuizQuestion_KeyOutput!]! @fdc_generated(from: "QuizQuestion", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `QuizResponse` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quizResponse_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [QuizResponse_Data!]!
  ): [QuizResponse_KeyOutput!]! @fdc_generated(from: "QuizResponse", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SourceMaterial` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sourceMaterial_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SourceMaterial_Data!]!
  ): [SourceMaterial_KeyOutput!]! @fdc_generated(from: "SourceMaterial", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SourceMaterialActivity` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sourceMaterialActivity_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SourceMaterialActivity_Data!]!
  ): [SourceMaterialActivity_KeyOutput!]! @fdc_generated(from: "SourceMaterialActivity", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SourceMaterialFolder` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sourceMaterialFolder_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SourceMaterialFolder_Data!]!
  ): [SourceMaterialFolder_KeyOutput!]! @fdc_generated(from: "SourceMaterialFolder", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SourceMaterialTag` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sourceMaterialTag_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SourceMaterialTag_Data!]!
  ): [SourceMaterialTag_KeyOutput!]! @fdc_generated(from: "SourceMaterialTag", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SourceMaterialTagAssignment` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sourceMaterialTagAssignment_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SourceMaterialTagAssignment_Data!]!
  ): [SourceMaterialTagAssignment_KeyOutput!]! @fdc_generated(from: "SourceMaterialTagAssignment", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserCourseProgress` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userCourseProgress_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserCourseProgress_Data!]!
  ): [UserCourseProgress_KeyOutput!]! @fdc_generated(from: "UserCourseProgress", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserFavorite` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userFavorite_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserFavorite_Data!]!
  ): [UserFavorite_KeyOutput!]! @fdc_generated(from: "UserFavorite", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserLessonProgress` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userLessonProgress_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserLessonProgress_Data!]!
  ): [UserLessonProgress_KeyOutput!]! @fdc_generated(from: "UserLessonProgress", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `AnswerChoice` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AnswerChoice`.
  """
  answerChoice_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AnswerChoice_Data!
  ): AnswerChoice_KeyOutput! @fdc_generated(from: "AnswerChoice", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ContentSourceLink` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ContentSourceLink`.
  """
  contentSourceLink_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ContentSourceLink_Data!
  ): ContentSourceLink_KeyOutput! @fdc_generated(from: "ContentSourceLink", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Course` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Course`.
  """
  course_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Course_Data!
  ): Course_KeyOutput! @fdc_generated(from: "Course", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Formula` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Formula`.
  """
  formula_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Formula_Data!
  ): Formula_KeyOutput! @fdc_generated(from: "Formula", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `FormulaSection` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `FormulaSection`.
  """
  formulaSection_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: FormulaSection_Data!
  ): FormulaSection_KeyOutput! @fdc_generated(from: "FormulaSection", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `GlossaryNote` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GlossaryNote`.
  """
  glossaryNote_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: GlossaryNote_Data!
  ): GlossaryNote_KeyOutput! @fdc_generated(from: "GlossaryNote", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `GlossaryTerm` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GlossaryTerm`.
  """
  glossaryTerm_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: GlossaryTerm_Data!
  ): GlossaryTerm_KeyOutput! @fdc_generated(from: "GlossaryTerm", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `IngestionJob` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `IngestionJob`.
  """
  ingestionJob_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: IngestionJob_Data!
  ): IngestionJob_KeyOutput! @fdc_generated(from: "IngestionJob", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Lesson` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Lesson`.
  """
  lesson_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Lesson_Data!
  ): Lesson_KeyOutput! @fdc_generated(from: "Lesson", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `LessonNote` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LessonNote`.
  """
  lessonNote_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: LessonNote_Data!
  ): LessonNote_KeyOutput! @fdc_generated(from: "LessonNote", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `LessonVersion` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LessonVersion`.
  """
  lessonVersion_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: LessonVersion_Data!
  ): LessonVersion_KeyOutput! @fdc_generated(from: "LessonVersion", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Module` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Module`.
  """
  module_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Module_Data!
  ): Module_KeyOutput! @fdc_generated(from: "Module", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Question` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Question`.
  """
  question_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Question_Data!
  ): Question_KeyOutput! @fdc_generated(from: "Question", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Quiz` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Quiz`.
  """
  quiz_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Quiz_Data!
  ): Quiz_KeyOutput! @fdc_generated(from: "Quiz", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `QuizAttempt` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuizAttempt`.
  """
  quizAttempt_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: QuizAttempt_Data!
  ): QuizAttempt_KeyOutput! @fdc_generated(from: "QuizAttempt", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `QuizQuestion` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuizQuestion`.
  """
  quizQuestion_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: QuizQuestion_Data!
  ): QuizQuestion_KeyOutput! @fdc_generated(from: "QuizQuestion", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `QuizResponse` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuizResponse`.
  """
  quizResponse_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: QuizResponse_Data!
  ): QuizResponse_KeyOutput! @fdc_generated(from: "QuizResponse", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SourceMaterial` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SourceMaterial`.
  """
  sourceMaterial_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SourceMaterial_Data!
  ): SourceMaterial_KeyOutput! @fdc_generated(from: "SourceMaterial", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SourceMaterialActivity` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SourceMaterialActivity`.
  """
  sourceMaterialActivity_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SourceMaterialActivity_Data!
  ): SourceMaterialActivity_KeyOutput! @fdc_generated(from: "SourceMaterialActivity", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SourceMaterialFolder` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SourceMaterialFolder`.
  """
  sourceMaterialFolder_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SourceMaterialFolder_Data!
  ): SourceMaterialFolder_KeyOutput! @fdc_generated(from: "SourceMaterialFolder", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SourceMaterialTag` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SourceMaterialTag`.
  """
  sourceMaterialTag_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SourceMaterialTag_Data!
  ): SourceMaterialTag_KeyOutput! @fdc_generated(from: "SourceMaterialTag", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SourceMaterialTagAssignment` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SourceMaterialTagAssignment`.
  """
  sourceMaterialTagAssignment_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SourceMaterialTagAssignment_Data!
  ): SourceMaterialTagAssignment_KeyOutput! @fdc_generated(from: "SourceMaterialTagAssignment", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserCourseProgress` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserCourseProgress`.
  """
  userCourseProgress_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserCourseProgress_Data!
  ): UserCourseProgress_KeyOutput! @fdc_generated(from: "UserCourseProgress", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserFavorite` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserFavorite`.
  """
  userFavorite_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserFavorite_Data!
  ): UserFavorite_KeyOutput! @fdc_generated(from: "UserFavorite", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserLessonProgress` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserLessonProgress`.
  """
  userLessonProgress_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserLessonProgress_Data!
  ): UserLessonProgress_KeyOutput! @fdc_generated(from: "UserLessonProgress", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `AnswerChoice` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AnswerChoice`.
  """
  answerChoice_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AnswerChoice_Data!]!
  ): [AnswerChoice_KeyOutput!]! @fdc_generated(from: "AnswerChoice", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ContentSourceLink` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ContentSourceLink`.
  """
  contentSourceLink_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ContentSourceLink_Data!]!
  ): [ContentSourceLink_KeyOutput!]! @fdc_generated(from: "ContentSourceLink", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Course` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Course`.
  """
  course_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Course_Data!]!
  ): [Course_KeyOutput!]! @fdc_generated(from: "Course", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Formula` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Formula`.
  """
  formula_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Formula_Data!]!
  ): [Formula_KeyOutput!]! @fdc_generated(from: "Formula", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `FormulaSection` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `FormulaSection`.
  """
  formulaSection_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [FormulaSection_Data!]!
  ): [FormulaSection_KeyOutput!]! @fdc_generated(from: "FormulaSection", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `GlossaryNote` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GlossaryNote`.
  """
  glossaryNote_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [GlossaryNote_Data!]!
  ): [GlossaryNote_KeyOutput!]! @fdc_generated(from: "GlossaryNote", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `GlossaryTerm` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GlossaryTerm`.
  """
  glossaryTerm_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [GlossaryTerm_Data!]!
  ): [GlossaryTerm_KeyOutput!]! @fdc_generated(from: "GlossaryTerm", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `IngestionJob` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `IngestionJob`.
  """
  ingestionJob_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [IngestionJob_Data!]!
  ): [IngestionJob_KeyOutput!]! @fdc_generated(from: "IngestionJob", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Lesson` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Lesson`.
  """
  lesson_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Lesson_Data!]!
  ): [Lesson_KeyOutput!]! @fdc_generated(from: "Lesson", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `LessonNote` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LessonNote`.
  """
  lessonNote_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [LessonNote_Data!]!
  ): [LessonNote_KeyOutput!]! @fdc_generated(from: "LessonNote", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `LessonVersion` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LessonVersion`.
  """
  lessonVersion_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [LessonVersion_Data!]!
  ): [LessonVersion_KeyOutput!]! @fdc_generated(from: "LessonVersion", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Module` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Module`.
  """
  module_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Module_Data!]!
  ): [Module_KeyOutput!]! @fdc_generated(from: "Module", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Question` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Question`.
  """
  question_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Question_Data!]!
  ): [Question_KeyOutput!]! @fdc_generated(from: "Question", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Quiz` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Quiz`.
  """
  quiz_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Quiz_Data!]!
  ): [Quiz_KeyOutput!]! @fdc_generated(from: "Quiz", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `QuizAttempt` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuizAttempt`.
  """
  quizAttempt_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [QuizAttempt_Data!]!
  ): [QuizAttempt_KeyOutput!]! @fdc_generated(from: "QuizAttempt", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `QuizQuestion` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuizQuestion`.
  """
  quizQuestion_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [QuizQuestion_Data!]!
  ): [QuizQuestion_KeyOutput!]! @fdc_generated(from: "QuizQuestion", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `QuizResponse` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuizResponse`.
  """
  quizResponse_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [QuizResponse_Data!]!
  ): [QuizResponse_KeyOutput!]! @fdc_generated(from: "QuizResponse", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SourceMaterial` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SourceMaterial`.
  """
  sourceMaterial_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SourceMaterial_Data!]!
  ): [SourceMaterial_KeyOutput!]! @fdc_generated(from: "SourceMaterial", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SourceMaterialActivity` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SourceMaterialActivity`.
  """
  sourceMaterialActivity_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SourceMaterialActivity_Data!]!
  ): [SourceMaterialActivity_KeyOutput!]! @fdc_generated(from: "SourceMaterialActivity", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SourceMaterialFolder` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SourceMaterialFolder`.
  """
  sourceMaterialFolder_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SourceMaterialFolder_Data!]!
  ): [SourceMaterialFolder_KeyOutput!]! @fdc_generated(from: "SourceMaterialFolder", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SourceMaterialTag` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SourceMaterialTag`.
  """
  sourceMaterialTag_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SourceMaterialTag_Data!]!
  ): [SourceMaterialTag_KeyOutput!]! @fdc_generated(from: "SourceMaterialTag", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SourceMaterialTagAssignment` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SourceMaterialTagAssignment`.
  """
  sourceMaterialTagAssignment_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SourceMaterialTagAssignment_Data!]!
  ): [SourceMaterialTagAssignment_KeyOutput!]! @fdc_generated(from: "SourceMaterialTagAssignment", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserCourseProgress` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserCourseProgress`.
  """
  userCourseProgress_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserCourseProgress_Data!]!
  ): [UserCourseProgress_KeyOutput!]! @fdc_generated(from: "UserCourseProgress", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserFavorite` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserFavorite`.
  """
  userFavorite_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserFavorite_Data!]!
  ): [UserFavorite_KeyOutput!]! @fdc_generated(from: "UserFavorite", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserLessonProgress` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserLessonProgress`.
  """
  userLessonProgress_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserLessonProgress_Data!]!
  ): [UserLessonProgress_KeyOutput!]! @fdc_generated(from: "UserLessonProgress", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `AnswerChoice` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `AnswerChoice` or `null` if not found.
  """
  answerChoice_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AnswerChoice_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AnswerChoice_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AnswerChoice_Data!
  ): AnswerChoice_KeyOutput @fdc_generated(from: "AnswerChoice", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ContentSourceLink` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ContentSourceLink` or `null` if not found.
  """
  contentSourceLink_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ContentSourceLink_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ContentSourceLink_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ContentSourceLink_Data!
  ): ContentSourceLink_KeyOutput @fdc_generated(from: "ContentSourceLink", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Course` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Course` or `null` if not found.
  """
  course_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Course_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Course_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Course_Data!
  ): Course_KeyOutput @fdc_generated(from: "Course", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Formula` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Formula` or `null` if not found.
  """
  formula_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Formula_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Formula_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Formula_Data!
  ): Formula_KeyOutput @fdc_generated(from: "Formula", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `FormulaSection` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `FormulaSection` or `null` if not found.
  """
  formulaSection_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FormulaSection_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FormulaSection_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: FormulaSection_Data!
  ): FormulaSection_KeyOutput @fdc_generated(from: "FormulaSection", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `GlossaryNote` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `GlossaryNote` or `null` if not found.
  """
  glossaryNote_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GlossaryNote_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GlossaryNote_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: GlossaryNote_Data!
  ): GlossaryNote_KeyOutput @fdc_generated(from: "GlossaryNote", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `GlossaryTerm` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `GlossaryTerm` or `null` if not found.
  """
  glossaryTerm_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GlossaryTerm_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GlossaryTerm_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: GlossaryTerm_Data!
  ): GlossaryTerm_KeyOutput @fdc_generated(from: "GlossaryTerm", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `IngestionJob` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `IngestionJob` or `null` if not found.
  """
  ingestionJob_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: IngestionJob_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: IngestionJob_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: IngestionJob_Data!
  ): IngestionJob_KeyOutput @fdc_generated(from: "IngestionJob", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Lesson` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Lesson` or `null` if not found.
  """
  lesson_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Lesson_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Lesson_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Lesson_Data!
  ): Lesson_KeyOutput @fdc_generated(from: "Lesson", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `LessonNote` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `LessonNote` or `null` if not found.
  """
  lessonNote_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LessonNote_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LessonNote_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: LessonNote_Data!
  ): LessonNote_KeyOutput @fdc_generated(from: "LessonNote", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `LessonVersion` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `LessonVersion` or `null` if not found.
  """
  lessonVersion_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LessonVersion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LessonVersion_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: LessonVersion_Data!
  ): LessonVersion_KeyOutput @fdc_generated(from: "LessonVersion", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Module` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Module` or `null` if not found.
  """
  module_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Module_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Module_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Module_Data!
  ): Module_KeyOutput @fdc_generated(from: "Module", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Question` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Question` or `null` if not found.
  """
  question_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Question_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Question_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Question_Data!
  ): Question_KeyOutput @fdc_generated(from: "Question", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Quiz` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Quiz` or `null` if not found.
  """
  quiz_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Quiz_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Quiz_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Quiz_Data!
  ): Quiz_KeyOutput @fdc_generated(from: "Quiz", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `QuizAttempt` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `QuizAttempt` or `null` if not found.
  """
  quizAttempt_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: QuizAttempt_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuizAttempt_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: QuizAttempt_Data!
  ): QuizAttempt_KeyOutput @fdc_generated(from: "QuizAttempt", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `QuizQuestion` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `QuizQuestion` or `null` if not found.
  """
  quizQuestion_update(
    """
    The key used to identify the object.
    """
    key: QuizQuestion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuizQuestion_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: QuizQuestion_Data!
  ): QuizQuestion_KeyOutput @fdc_generated(from: "QuizQuestion", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `QuizResponse` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `QuizResponse` or `null` if not found.
  """
  quizResponse_update(
    """
    The key used to identify the object.
    """
    key: QuizResponse_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuizResponse_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: QuizResponse_Data!
  ): QuizResponse_KeyOutput @fdc_generated(from: "QuizResponse", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SourceMaterial` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SourceMaterial` or `null` if not found.
  """
  sourceMaterial_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SourceMaterial_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SourceMaterial_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SourceMaterial_Data!
  ): SourceMaterial_KeyOutput @fdc_generated(from: "SourceMaterial", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SourceMaterialActivity` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SourceMaterialActivity` or `null` if not found.
  """
  sourceMaterialActivity_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SourceMaterialActivity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SourceMaterialActivity_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SourceMaterialActivity_Data!
  ): SourceMaterialActivity_KeyOutput @fdc_generated(from: "SourceMaterialActivity", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SourceMaterialFolder` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SourceMaterialFolder` or `null` if not found.
  """
  sourceMaterialFolder_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SourceMaterialFolder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SourceMaterialFolder_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SourceMaterialFolder_Data!
  ): SourceMaterialFolder_KeyOutput @fdc_generated(from: "SourceMaterialFolder", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SourceMaterialTag` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SourceMaterialTag` or `null` if not found.
  """
  sourceMaterialTag_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SourceMaterialTag_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SourceMaterialTag_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SourceMaterialTag_Data!
  ): SourceMaterialTag_KeyOutput @fdc_generated(from: "SourceMaterialTag", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SourceMaterialTagAssignment` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SourceMaterialTagAssignment` or `null` if not found.
  """
  sourceMaterialTagAssignment_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SourceMaterialTagAssignment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SourceMaterialTagAssignment_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SourceMaterialTagAssignment_Data!
  ): SourceMaterialTagAssignment_KeyOutput @fdc_generated(from: "SourceMaterialTagAssignment", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserCourseProgress` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserCourseProgress` or `null` if not found.
  """
  userCourseProgress_update(
    """
    The key used to identify the object.
    """
    key: UserCourseProgress_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserCourseProgress_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserCourseProgress_Data!
  ): UserCourseProgress_KeyOutput @fdc_generated(from: "UserCourseProgress", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserFavorite` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserFavorite` or `null` if not found.
  """
  userFavorite_update(
    """
    The key used to identify the object.
    """
    key: UserFavorite_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserFavorite_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserFavorite_Data!
  ): UserFavorite_KeyOutput @fdc_generated(from: "UserFavorite", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserLessonProgress` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserLessonProgress` or `null` if not found.
  """
  userLessonProgress_update(
    """
    The key used to identify the object.
    """
    key: UserLessonProgress_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserLessonProgress_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserLessonProgress_Data!
  ): UserLessonProgress_KeyOutput @fdc_generated(from: "UserLessonProgress", purpose: UPDATE_SINGLE)
  """
  ✨ Update `AnswerChoice` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  answerChoice_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AnswerChoice_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AnswerChoice_Data!
  ): Int! @fdc_generated(from: "AnswerChoice", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ContentSourceLink` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  contentSourceLink_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ContentSourceLink_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ContentSourceLink_Data!
  ): Int! @fdc_generated(from: "ContentSourceLink", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Course` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  course_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Course_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Course_Data!
  ): Int! @fdc_generated(from: "Course", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Formula` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  formula_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Formula_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Formula_Data!
  ): Int! @fdc_generated(from: "Formula", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `FormulaSection` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  formulaSection_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: FormulaSection_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: FormulaSection_Data!
  ): Int! @fdc_generated(from: "FormulaSection", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `GlossaryNote` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  glossaryNote_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: GlossaryNote_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: GlossaryNote_Data!
  ): Int! @fdc_generated(from: "GlossaryNote", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `GlossaryTerm` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  glossaryTerm_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: GlossaryTerm_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: GlossaryTerm_Data!
  ): Int! @fdc_generated(from: "GlossaryTerm", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `IngestionJob` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  ingestionJob_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: IngestionJob_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: IngestionJob_Data!
  ): Int! @fdc_generated(from: "IngestionJob", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Lesson` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  lesson_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Lesson_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Lesson_Data!
  ): Int! @fdc_generated(from: "Lesson", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `LessonNote` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  lessonNote_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: LessonNote_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: LessonNote_Data!
  ): Int! @fdc_generated(from: "LessonNote", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `LessonVersion` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  lessonVersion_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: LessonVersion_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: LessonVersion_Data!
  ): Int! @fdc_generated(from: "LessonVersion", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Module` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  module_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Module_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Module_Data!
  ): Int! @fdc_generated(from: "Module", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Question` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  question_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Question_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Question_Data!
  ): Int! @fdc_generated(from: "Question", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Quiz` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  quiz_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Quiz_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Quiz_Data!
  ): Int! @fdc_generated(from: "Quiz", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `QuizAttempt` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  quizAttempt_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: QuizAttempt_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: QuizAttempt_Data!
  ): Int! @fdc_generated(from: "QuizAttempt", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `QuizQuestion` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  quizQuestion_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: QuizQuestion_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: QuizQuestion_Data!
  ): Int! @fdc_generated(from: "QuizQuestion", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `QuizResponse` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  quizResponse_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: QuizResponse_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: QuizResponse_Data!
  ): Int! @fdc_generated(from: "QuizResponse", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SourceMaterial` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  sourceMaterial_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SourceMaterial_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SourceMaterial_Data!
  ): Int! @fdc_generated(from: "SourceMaterial", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SourceMaterialActivity` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  sourceMaterialActivity_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SourceMaterialActivity_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SourceMaterialActivity_Data!
  ): Int! @fdc_generated(from: "SourceMaterialActivity", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SourceMaterialFolder` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  sourceMaterialFolder_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SourceMaterialFolder_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SourceMaterialFolder_Data!
  ): Int! @fdc_generated(from: "SourceMaterialFolder", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SourceMaterialTag` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  sourceMaterialTag_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SourceMaterialTag_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SourceMaterialTag_Data!
  ): Int! @fdc_generated(from: "SourceMaterialTag", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SourceMaterialTagAssignment` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  sourceMaterialTagAssignment_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SourceMaterialTagAssignment_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SourceMaterialTagAssignment_Data!
  ): Int! @fdc_generated(from: "SourceMaterialTagAssignment", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserCourseProgress` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userCourseProgress_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserCourseProgress_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserCourseProgress_Data!
  ): Int! @fdc_generated(from: "UserCourseProgress", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserFavorite` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userFavorite_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserFavorite_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserFavorite_Data!
  ): Int! @fdc_generated(from: "UserFavorite", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserLessonProgress` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userLessonProgress_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserLessonProgress_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserLessonProgress_Data!
  ): Int! @fdc_generated(from: "UserLessonProgress", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `AnswerChoice` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  answerChoice_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AnswerChoice_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AnswerChoice_FirstRow
  ): AnswerChoice_KeyOutput @fdc_generated(from: "AnswerChoice", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ContentSourceLink` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  contentSourceLink_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ContentSourceLink_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ContentSourceLink_FirstRow
  ): ContentSourceLink_KeyOutput @fdc_generated(from: "ContentSourceLink", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Course` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  course_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Course_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Course_FirstRow
  ): Course_KeyOutput @fdc_generated(from: "Course", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Formula` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  formula_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Formula_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Formula_FirstRow
  ): Formula_KeyOutput @fdc_generated(from: "Formula", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `FormulaSection` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  formulaSection_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FormulaSection_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FormulaSection_FirstRow
  ): FormulaSection_KeyOutput @fdc_generated(from: "FormulaSection", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `GlossaryNote` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  glossaryNote_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GlossaryNote_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GlossaryNote_FirstRow
  ): GlossaryNote_KeyOutput @fdc_generated(from: "GlossaryNote", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `GlossaryTerm` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  glossaryTerm_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GlossaryTerm_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GlossaryTerm_FirstRow
  ): GlossaryTerm_KeyOutput @fdc_generated(from: "GlossaryTerm", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `IngestionJob` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  ingestionJob_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: IngestionJob_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: IngestionJob_FirstRow
  ): IngestionJob_KeyOutput @fdc_generated(from: "IngestionJob", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Lesson` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  lesson_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Lesson_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Lesson_FirstRow
  ): Lesson_KeyOutput @fdc_generated(from: "Lesson", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `LessonNote` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  lessonNote_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LessonNote_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LessonNote_FirstRow
  ): LessonNote_KeyOutput @fdc_generated(from: "LessonNote", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `LessonVersion` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  lessonVersion_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LessonVersion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LessonVersion_FirstRow
  ): LessonVersion_KeyOutput @fdc_generated(from: "LessonVersion", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Module` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  module_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Module_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Module_FirstRow
  ): Module_KeyOutput @fdc_generated(from: "Module", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Question` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  question_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Question_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Question_FirstRow
  ): Question_KeyOutput @fdc_generated(from: "Question", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Quiz` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  quiz_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Quiz_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Quiz_FirstRow
  ): Quiz_KeyOutput @fdc_generated(from: "Quiz", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `QuizAttempt` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  quizAttempt_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: QuizAttempt_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuizAttempt_FirstRow
  ): QuizAttempt_KeyOutput @fdc_generated(from: "QuizAttempt", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `QuizQuestion` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  quizQuestion_delete(
    """
    The key used to identify the object.
    """
    key: QuizQuestion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuizQuestion_FirstRow
  ): QuizQuestion_KeyOutput @fdc_generated(from: "QuizQuestion", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `QuizResponse` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  quizResponse_delete(
    """
    The key used to identify the object.
    """
    key: QuizResponse_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuizResponse_FirstRow
  ): QuizResponse_KeyOutput @fdc_generated(from: "QuizResponse", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SourceMaterial` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  sourceMaterial_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SourceMaterial_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SourceMaterial_FirstRow
  ): SourceMaterial_KeyOutput @fdc_generated(from: "SourceMaterial", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SourceMaterialActivity` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  sourceMaterialActivity_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SourceMaterialActivity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SourceMaterialActivity_FirstRow
  ): SourceMaterialActivity_KeyOutput @fdc_generated(from: "SourceMaterialActivity", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SourceMaterialFolder` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  sourceMaterialFolder_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SourceMaterialFolder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SourceMaterialFolder_FirstRow
  ): SourceMaterialFolder_KeyOutput @fdc_generated(from: "SourceMaterialFolder", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SourceMaterialTag` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  sourceMaterialTag_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SourceMaterialTag_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SourceMaterialTag_FirstRow
  ): SourceMaterialTag_KeyOutput @fdc_generated(from: "SourceMaterialTag", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SourceMaterialTagAssignment` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  sourceMaterialTagAssignment_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SourceMaterialTagAssignment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SourceMaterialTagAssignment_FirstRow
  ): SourceMaterialTagAssignment_KeyOutput @fdc_generated(from: "SourceMaterialTagAssignment", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserCourseProgress` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userCourseProgress_delete(
    """
    The key used to identify the object.
    """
    key: UserCourseProgress_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserCourseProgress_FirstRow
  ): UserCourseProgress_KeyOutput @fdc_generated(from: "UserCourseProgress", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserFavorite` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userFavorite_delete(
    """
    The key used to identify the object.
    """
    key: UserFavorite_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserFavorite_FirstRow
  ): UserFavorite_KeyOutput @fdc_generated(from: "UserFavorite", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserLessonProgress` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userLessonProgress_delete(
    """
    The key used to identify the object.
    """
    key: UserLessonProgress_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserLessonProgress_FirstRow
  ): UserLessonProgress_KeyOutput @fdc_generated(from: "UserLessonProgress", purpose: DELETE_SINGLE)
  """
  ✨ Delete `AnswerChoice` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  answerChoice_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AnswerChoice_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AnswerChoice", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ContentSourceLink` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  contentSourceLink_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ContentSourceLink_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ContentSourceLink", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Course` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  course_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Course_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Course", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Formula` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  formula_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Formula_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Formula", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `FormulaSection` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  formulaSection_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: FormulaSection_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "FormulaSection", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `GlossaryNote` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  glossaryNote_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: GlossaryNote_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "GlossaryNote", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `GlossaryTerm` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  glossaryTerm_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: GlossaryTerm_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "GlossaryTerm", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `IngestionJob` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  ingestionJob_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: IngestionJob_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "IngestionJob", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Lesson` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  lesson_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Lesson_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Lesson", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `LessonNote` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  lessonNote_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: LessonNote_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "LessonNote", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `LessonVersion` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  lessonVersion_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: LessonVersion_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "LessonVersion", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Module` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  module_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Module_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Module", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Question` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  question_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Question_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Question", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Quiz` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  quiz_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Quiz_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Quiz", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `QuizAttempt` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  quizAttempt_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: QuizAttempt_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "QuizAttempt", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `QuizQuestion` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  quizQuestion_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: QuizQuestion_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "QuizQuestion", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `QuizResponse` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  quizResponse_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: QuizResponse_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "QuizResponse", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SourceMaterial` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  sourceMaterial_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SourceMaterial_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SourceMaterial", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SourceMaterialActivity` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  sourceMaterialActivity_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SourceMaterialActivity_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SourceMaterialActivity", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SourceMaterialFolder` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  sourceMaterialFolder_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SourceMaterialFolder_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SourceMaterialFolder", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SourceMaterialTag` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  sourceMaterialTag_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SourceMaterialTag_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SourceMaterialTag", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SourceMaterialTagAssignment` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  sourceMaterialTagAssignment_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SourceMaterialTagAssignment_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SourceMaterialTagAssignment", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserCourseProgress` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userCourseProgress_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserCourseProgress_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserCourseProgress", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserFavorite` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userFavorite_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserFavorite_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserFavorite", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserLessonProgress` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userLessonProgress_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserLessonProgress_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserLessonProgress", purpose: DELETE_MULTIPLE)
}
